"""initial schema

Revision ID: 9e9c98c2eb7f
Revises: 
Create Date: 2026-08-19 11:28:27.229143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9c98c2eb7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beds',
    sa.Column('bed_no', sa.String(), nullable=False),
    sa.Column('ward_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bed_no')
    )
    op.create_index(op.f('ix_beds_bed_no'), 'beds', ['bed_no'], unique=False)
    op.create_index(op.f('ix_beds_ward_id'), 'beds', ['ward_id'], unique=False)
    op.create_table('devices',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=False)
    op.create_table('handover_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('patient_token', sa.String(), nullable=False),
    sa.Column('bed_no', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('bundle_id', sa.String(), nullable=False),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('purged_aggregate_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handover_records_bed_no'), 'handover_records', ['bed_no'], unique=False)
    op.create_index(op.f('ix_handover_records_bundle_id'), 'handover_records', ['bundle_id'], unique=True)
    op.create_index(op.f('ix_handover_records_created_at'), 'handover_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_handover_records_device_id'), 'handover_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_handover_records_patient_token'), 'handover_records', ['patient_token'], unique=False)
    op.create_index(op.f('ix_handover_records_synced'), 'handover_records', ['synced'], unique=False)
    op.create_table('patients',
    sa.Column('patient_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('patient_token')
    )
    op.create_index(op.f('ix_patients_patient_token'), 'patients', ['patient_token'], unique=False)
    op.create_table('sync_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('bundle_id', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_attempts_acknowledged'), 'sync_attempts', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_sync_attempts_bundle_id'), 'sync_attempts', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_sync_attempts_created_at'), 'sync_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_attempts_device_id'), 'sync_attempts', ['device_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('bed_no', sa.String(), nullable=False),
    sa.Column('patient_token', sa.String(), nullable=False),
    sa.Column('alert_level', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_bed_no'), 'alerts', ['bed_no'], unique=False)
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_alerts_is_resolved'), 'alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_alerts_patient_token'), 'alerts', ['patient_token'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('pairings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_token', sa.String(), nullable=False),
    sa.Column('bed_no', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('paired_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('unpaired_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bed_no'], ['beds.bed_no'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['patient_token'], ['patients.patient_token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairings_bed_no'), 'pairings', ['bed_no'], unique=False)
    op.create_index(op.f('ix_pairings_device_id'), 'pairings', ['device_id'], unique=False)
    op.create_index(op.f('ix_pairings_is_active'), 'pairings', ['is_active'], unique=False)
    op.create_index(op.f('ix_pairings_paired_at'), 'pairings', ['paired_at'], unique=False)
    op.create_index(op.f('ix_pairings_patient_token'), 'pairings', ['patient_token'], unique=False)
    op.create_index('uq_pairing_bed_active', 'pairings', ['bed_no'], unique=True, sqlite_where=sa.text('is_active = 1'))
    op.create_index('uq_pairing_device_active', 'pairings', ['device_id'], unique=True, sqlite_where=sa.text('is_active = 1'))
    op.create_table('telemetry_aggregates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('patient_token', sa.String(), nullable=False),
    sa.Column('bed_no', sa.String(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('ppg_avg', sa.Float(), nullable=False),
    sa.Column('ppg_min', sa.Float(), nullable=False),
    sa.Column('ppg_max', sa.Float(), nullable=False),
    sa.Column('heart_rate_avg', sa.Float(), nullable=True),
    sa.Column('heart_rate_min', sa.Float(), nullable=True),
    sa.Column('heart_rate_max', sa.Float(), nullable=True),
    sa.Column('spo2_avg', sa.Float(), nullable=True),
    sa.Column('spo2_min', sa.Float(), nullable=True),
    sa.Column('spo2_max', sa.Float(), nullable=True),
    sa.Column('skin_temp_avg', sa.Float(), nullable=False),
    sa.Column('skin_temp_min', sa.Float(), nullable=True),
    sa.Column('skin_temp_max', sa.Float(), nullable=True),
    sa.Column('battery_latest', sa.Float(), nullable=False),
    sa.Column('max_accel_g', sa.Float(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_aggregates_bed_no'), 'telemetry_aggregates', ['bed_no'], unique=False)
    op.create_index(op.f('ix_telemetry_aggregates_created_at'), 'telemetry_aggregates', ['created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_aggregates_device_id'), 'telemetry_aggregates', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_aggregates_patient_token'), 'telemetry_aggregates', ['patient_token'], unique=False)
    op.create_table('forensic_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('patient_token', sa.String(), nullable=False),
    sa.Column('bed_no', sa.String(), nullable=False),
    sa.Column('frozen_payload_json', sa.String(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=False),
    sa.Column('block_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forensic_packages_alert_id'), 'forensic_packages', ['alert_id'], unique=False)
    op.create_index(op.f('ix_forensic_packages_bed_no'), 'forensic_packages', ['bed_no'], unique=False)
    op.create_index(op.f('ix_forensic_packages_block_hash'), 'forensic_packages', ['block_hash'], unique=True)
    op.create_index(op.f('ix_forensic_packages_created_at'), 'forensic_packages', ['created_at'], unique=False)
    op.create_index(op.f('ix_forensic_packages_device_id'), 'forensic_packages', ['device_id'], unique=False)
    op.create_index(op.f('ix_forensic_packages_patient_token'), 'forensic_packages', ['patient_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forensic_packages_patient_token'), table_name='forensic_packages')
    op.drop_index(op.f('ix_forensic_packages_device_id'), table_name='forensic_packages')
    op.drop_index(op.f('ix_forensic_packages_created_at'), table_name='forensic_packages')
    op.drop_index(op.f('ix_forensic_packages_block_hash'), table_name='forensic_packages')
    op.drop_index(op.f('ix_forensic_packages_bed_no'), table_name='forensic_packages')
    op.drop_index(op.f('ix_forensic_packages_alert_id'), table_name='forensic_packages')
    op.drop_table('forensic_packages')
    op.drop_index(op.f('ix_telemetry_aggregates_patient_token'), table_name='telemetry_aggregates')
    op.drop_index(op.f('ix_telemetry_aggregates_device_id'), table_name='telemetry_aggregates')
    op.drop_index(op.f('ix_telemetry_aggregates_created_at'), table_name='telemetry_aggregates')
    op.drop_index(op.f('ix_telemetry_aggregates_bed_no'), table_name='telemetry_aggregates')
    op.drop_table('telemetry_aggregates')
    op.drop_index('uq_pairing_device_active', table_name='pairings', sqlite_where=sa.text('is_active = 1'))
    op.drop_index('uq_pairing_bed_active', table_name='pairings', sqlite_where=sa.text('is_active = 1'))
    op.drop_index(op.f('ix_pairings_patient_token'), table_name='pairings')
    op.drop_index(op.f('ix_pairings_paired_at'), table_name='pairings')
    op.drop_index(op.f('ix_pairings_is_active'), table_name='pairings')
    op.drop_index(op.f('ix_pairings_device_id'), table_name='pairings')
    op.drop_index(op.f('ix_pairings_bed_no'), table_name='pairings')
    op.drop_table('pairings')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_patient_token'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_bed_no'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_sync_attempts_device_id'), table_name='sync_attempts')
    op.drop_index(op.f('ix_sync_attempts_created_at'), table_name='sync_attempts')
    op.drop_index(op.f('ix_sync_attempts_bundle_id'), table_name='sync_attempts')
    op.drop_index(op.f('ix_sync_attempts_acknowledged'), table_name='sync_attempts')
    op.drop_table('sync_attempts')
    op.drop_index(op.f('ix_patients_patient_token'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_handover_records_synced'), table_name='handover_records')
    op.drop_index(op.f('ix_handover_records_patient_token'), table_name='handover_records')
    op.drop_index(op.f('ix_handover_records_device_id'), table_name='handover_records')
    op.drop_index(op.f('ix_handover_records_created_at'), table_name='handover_records')
    op.drop_index(op.f('ix_handover_records_bundle_id'), table_name='handover_records')
    op.drop_index(op.f('ix_handover_records_bed_no'), table_name='handover_records')
    op.drop_table('handover_records')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_beds_ward_id'), table_name='beds')
    op.drop_index(op.f('ix_beds_bed_no'), table_name='beds')
    op.drop_table('beds')
    # ### end Alembic commands ###
